// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSIXjq0E-og3CyqupI945H4uxA7nuay6U',
    appId: '1:629207840365:web:105a5cd77ddc57e37ab164',
    messagingSenderId: '629207840365',
    projectId: 'fir-demo-6022f',
    authDomain: 'fir-demo-6022f.firebaseapp.com',
    storageBucket: 'fir-demo-6022f.firebasestorage.app',
    measurementId: 'G-ZRTJB1Q07X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnLIjddwbblISrynbx2M5puLOQytYwv5M',
    appId: '1:629207840365:android:4026c82c5da78bba7ab164',
    messagingSenderId: '629207840365',
    projectId: 'fir-demo-6022f',
    storageBucket: 'fir-demo-6022f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8oH-iPd2Xihw8s81fg-WQfTo_iYTSrHw',
    appId: '1:629207840365:ios:39bd4e87536d75f87ab164',
    messagingSenderId: '629207840365',
    projectId: 'fir-demo-6022f',
    storageBucket: 'fir-demo-6022f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8oH-iPd2Xihw8s81fg-WQfTo_iYTSrHw',
    appId: '1:629207840365:ios:39bd4e87536d75f87ab164',
    messagingSenderId: '629207840365',
    projectId: 'fir-demo-6022f',
    storageBucket: 'fir-demo-6022f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSIXjq0E-og3CyqupI945H4uxA7nuay6U',
    appId: '1:629207840365:web:c50858ed789c19007ab164',
    messagingSenderId: '629207840365',
    projectId: 'fir-demo-6022f',
    authDomain: 'fir-demo-6022f.firebaseapp.com',
    storageBucket: 'fir-demo-6022f.firebasestorage.app',
    measurementId: 'G-QYJEH11227',
  );
}
